### ISSUE TITLE
レイアウト/スタイルのカスタマイズ（Tailwindクラスの一部上書き許可）

### ISSUE THREAD

**Issue by kamoshika-san** [kamoshika-san/TextUI-Designer#13]
# スタイルトークンベースのテーマシステム提案

## 概要

TextUI Designerでは、デフォルトでTailwind CSSベースのスタイルが各コンポーネントに適用されます。  
しかし、プロジェクトごとに「ブランドカラーや独自のUIルールを反映したい」「デザインシステムとの一貫性を保ちたい」といったニーズに応えるため、**スタイルトークンベースのテーマシステム**を提供します。

このアプローチにより、個別の`class`プロパティ追加による開発体験の低下を回避し、TextUI Designerの哲学（省入力 × 可読性、曖昧さゼロ、即時フィードバック）を維持しながら、柔軟なカスタマイズを実現します。

---

### 1. **テーマファイルによる一元管理**
- プロジェクトルートに`textui-theme.yml`ファイルを配置
- デザイントークン（色、スペーシング、タイポグラフィなど）を一箇所で定義
- コンポーネント固有のスタイルも含めて管理

### 2. **デザイントークンの自動適用**
- テーマファイルで定義したトークンが自動的に全コンポーネントに適用
- CSS変数として変換され、WebViewで即座に反映
- 個別の`class`指定が不要でDSLの簡潔性を維持

### 3. **型安全性とIntelliSense**
- テーマファイルのスキーマ検証
- トークン名の補完機能
- 存在しないトークン名のエラー検出

### 4. **動的テーマ切り替え**
- ライト/ダークテーマの切り替え
- 複数テーマの切り替え
- プレビューでの即座な反映

---

## テーマファイルの例

```yaml
# textui-theme.yml
theme:
  name: "corporate-brand"
  version: "1.0.0"
  
  # デザイントークン
  tokens:
    colors:
      primary: "#3B82F6"
      secondary: "#6B7280"
      success: "#10B981"
      warning: "#F59E0B"
      error: "#EF4444"
      background: "#1F2937"
      surface: "#374151"
      text:
        primary: "#F9FAFB"
        secondary: "#D1D5DB"
        muted: "#9CA3AF"
    
    spacing:
      xs: "0.25rem"
      sm: "0.5rem"
      md: "1rem"
      lg: "1.5rem"
      xl: "2rem"
    
    typography:
      fontFamily: "Inter, system-ui, sans-serif"
      fontSize:
        xs: "0.75rem"
        sm: "0.875rem"
        base: "1rem"
        lg: "1.125rem"
        xl: "1.25rem"
        "2xl": "1.5rem"
        "3xl": "1.875rem"
        "4xl": "2.25rem"
    
    borderRadius:
      sm: "0.125rem"
      md: "0.375rem"
      lg: "0.5rem"
      xl: "0.75rem"
    
    shadows:
      sm: "0 1px 2px 0 rgba(0, 0, 0, 0.05)"
      md: "0 4px 6px -1px rgba(0, 0, 0, 0.1)"
      lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1)"

  # コンポーネント固有のスタイル
  components:
    button:
      primary:
        backgroundColor: "var(--color-primary)"
        color: "white"
        padding: "var(--spacing-sm) var(--spacing-md)"
        borderRadius: "var(--border-radius-md)"
      secondary:
        backgroundColor: "var(--color-secondary)"
        color: "white"
        padding: "var(--spacing-sm) var(--spacing-md)"
        borderRadius: "var(--border-radius-md)"
    
    alert:
      info:
        backgroundColor: "rgba(59, 130, 246, 0.1)"
        borderColor: "var(--color-primary)"
        color: "var(--color-primary)"
      success:
        backgroundColor: "rgba(16, 185, 129, 0.1)"
        borderColor: "var(--color-success)"
        color: "var(--color-success)"
```

---

### テーマ適用前（現在の記法）
```yaml
page:
  id: sample
  title: "サンプル"
  layout: vertical
  components:
    - Text:
        variant: h1
        value: "タイトル"
    
    - Button:
        kind: primary
        label: "送信"
    
    - Alert:
        variant: success
        message: "成功しました"
```

### テーマ適用後（同じ記法で自動適用）
```yaml
# textui-theme.yml で定義したスタイルが自動適用される
page:
  id: sample
  title: "サンプル"
  layout: vertical
  components:
    - Text:
        variant: h1
        value: "タイトル"  # テーマの typography.fontSize.4xl が適用
    
    - Button:
        kind: primary
        label: "送信"     # テーマの components.button.primary が適用
    
    - Alert:
        variant: success
        message: "成功しました"  # テーマの components.alert.success が適用
```

---

### **開発体験の向上**
- **省入力**: 個別の`class`指定が不要
- **可読性**: DSLが簡潔に保たれる
- **型安全性**: トークン名の補完・検証が可能

### **保守性の向上**
- **一元管理**: スタイル定義が一箇所に集約
- **一貫性**: デザインシステムの統一が保証
- **再利用性**: プロジェクト間でテーマを共有可能

### **拡張性**
- **テーマ切り替え**: ライト/ダークテーマの動的切り替え
- **ブランド対応**: 企業ブランドカラーの簡単適用
- **レスポンシブ**: デバイス別のスタイル調整

---

### Phase 1: テーマシステム基盤（MVP）
- [x] テーマファイルの読み込み機能
- [x] CSS変数への変換機能
- [x] WebViewへの動的適用
- [x] 基本的なデザイントークン（色、スペーシング）

### Phase 2: コンポーネント統合
- [x] 既存コンポーネントのテーマ対応
- [x] デフォルトテーマの提供
- [x] フォールバック機能
- [x] コンポーネント固有スタイルの定義

### Phase 3: 開発者体験
- [x] IntelliSense対応
- [x] テーマプレビュー機能
- [x] テーマエクスポート機能
- [x] テーマ切り替えUI

### Phase 4: 高度な機能
- [x] 複数テーマの管理
- [ ] テーマの継承・拡張
- [x] レスポンシブ対応
- [x] アニメーション・トランジション

---

### アーキテクチャ
```
Extension Host
 ├─ ThemeManager          # テーマファイルの読み込み・管理
 ├─ TokenProcessor        # デザイントークンの処理
 ├─ CSSVariableGenerator  # CSS変数の生成
 └─ WebViewThemeApplier   # WebViewへの適用

WebView (iframe)
 ├─ CSS Variables         # 動的に生成されたCSS変数
 ├─ Theme-aware Components # テーマ対応コンポーネント
 └─ Dynamic Style Updates # リアルタイムスタイル更新
```

### 主要クラス
```typescript
// ThemeManager: テーマの読み込み・管理
export class ThemeManager {
  async loadTheme(themePath: string): Promise<void>
  generateCSSVariables(theme: ThemeConfig): string
  applyThemeToWebView(webview: vscode.WebviewPanel): void
}

// TokenProcessor: デザイントークンの処理
export class TokenProcessor {
  processColorTokens(tokens: ColorTokens): CSSVariables
  processSpacingTokens(tokens: SpacingTokens): CSSVariables
  processTypographyTokens(tokens: TypographyTokens): CSSVariables
}
```

---

### 1. **テーママーケットプレイス**
- コミュニティによるテーマの共有
- 人気テーマのランキング
- テーマの評価・レビュー機能

### 2. **AI支援テーマ生成**
- ブランドガイドラインからの自動テーマ生成
- 既存デザインからのテーマ抽出
- アクセシビリティを考慮したテーマ提案

### 3. **高度なカスタマイズ**
- コンポーネントレベルのスタイルオーバーライド
- 条件付きスタイル（状態、デバイス、ユーザー設定）
- アニメーション・トランジションの定義

---

**このテーマシステムにより、TextUI Designerは「省入力・型安全・即時プレビュー」の強みを維持しつつ、プロジェクト固有のデザイン要件にも柔軟に対応できる拡張性を実現します。**
