### ISSUE TITLE
テーマ継承・拡張システムの実装

### ISSUE THREAD

**Issue by kamoshika-san** [kamoshika-san/TextUI-Designer#44]
## 概要

TextUI Designerの既存テーマシステム（Issue #13完了）を基盤として、**テーマの継承・拡張機能**を実装します。

基底テーマから部分的にカスタマイズしたテーマを作成できるようにすることで、テーマの再利用性と保守性を大幅に向上させ、大規模プロジェクトや複数プロダクト間でのデザインシステム統一を実現します。

---

### 現在のテーマシステムの制約

現在のTextUI Designerは高品質なテーマシステムを搭載していますが、以下の課題があります：

- **重複定義**: 類似テーマで共通部分を毎回記述する必要
- **保守コスト**: ベーステーマの変更時に派生テーマを個別更新
- **一貫性の維持困難**: 複数テーマ間でのデザイン統一が手動作業
- **大規模プロジェクト対応**: 企業での複数プロダクト間統一が困難

### 継承システムによる解決

```yaml
# base-corporate-theme.yml（基底テーマ）
theme:
  name: "Corporate Base Theme"
  tokens:
    color:
      primary: "#1E40AF"
      secondary: "#64748B"
    # ... 共通設定

---

# product-a-theme.yml（継承テーマ）
theme:
  name: "Product A Theme"
  extends: "./base-corporate-theme.yml"  # 継承指定
  tokens:
    color:
      primary: "#3B82F6"  # プライマリカラーのみ上書き
      # secondary は基底テーマから継承
```

---

#### `extends` キーワードによる継承
```yaml
theme:
  name: "Child Theme"
  extends: "./parent-theme.yml"  # 相対パス指定
  # または
  extends: "npm:@company/base-theme"  # npm パッケージ指定（将来拡張）
  
  # 上書きしたい部分のみを記述
  tokens:
    color:
      primary: "#新しい色"  # 基底テーマのprimaryを上書き
```

#### 継承の優先順位
1. **子テーマの設定** → 基底テーマより優先
2. **基底テーマの設定** → 子テーマで未定義の場合に適用
3. **デフォルトテーマ** → 両方で未定義の場合のフォールバック

### 2. **深い階層での部分上書き**

```yaml
# parent-theme.yml
theme:
  tokens:
    color:
      text:
        primary: "#111827"
        secondary: "#6B7280"
        muted: "#9CA3AF"
  components:
    button:
      primary:
        backgroundColor: "var(--color-primary)"
        color: "white"
        padding: "8px 16px"

---

# child-theme.yml
theme:
  extends: "./parent-theme.yml"
  tokens:
    color:
      text:
        primary: "#000000"  # text.primaryのみ上書き
        # secondary, muted は親から継承
  components:
    button:
      primary:
        backgroundColor: "#FF6B6B"  # backgroundColorのみ上書き
        # color, padding は親から継承
```

### 3. **多重継承（チェーン継承）**

```yaml
# base-theme.yml（ルート）
theme:
  name: "Base Theme"
  tokens: { ... }

---

# corporate-theme.yml（中間）
theme:
  extends: "./base-theme.yml"
  name: "Corporate Theme"
  tokens:
    color:
      primary: "#1E40AF"

---

# product-theme.yml（末端）
theme:
  extends: "./corporate-theme.yml"
  name: "Product Theme"
  tokens:
    color:
      secondary: "#FF6B6B"
```

**継承チェーン**: `product-theme.yml` → `corporate-theme.yml` → `base-theme.yml` → `default`

#### デフォルト戦略: 深いマージ
```yaml
# 親テーマ
components:
  button:
    primary: { backgroundColor: "blue", color: "white" }
    secondary: { backgroundColor: "gray", color: "black" }

# 子テーマ
components:
  button:
    primary: { backgroundColor: "red" }  # colorは親から継承
    # secondaryは完全に親から継承

# 結果
components:
  button:
    primary: { backgroundColor: "red", color: "white" }
    secondary: { backgroundColor: "gray", color: "black" }
```

#### 明示的な上書き戦略
```yaml
theme:
  extends: "./parent.yml"
  mergeStrategy:
    "tokens.color": "replace"      # 完全置換
    "components.button": "merge"   # 深いマージ（デフォルト）
```

---

### 1. **ThemeManager の拡張**

```typescript
export class ThemeManager {
  private inheritanceCache = new Map<string, any>();
  
  /**
   * 継承チェーンを解決してテーマを読み込み
   */
  async loadTheme(themePath?: string): Promise<void> {
    const resolved = await this.resolveInheritance(themePath);
    this.tokens = resolved.tokens || this.defaultTokens;
    this.components = resolved.components || this.defaultComponents;
  }
  
  /**
   * 継承チェーンを再帰的に解決
   */
  private async resolveInheritance(
    themePath: string, 
    visited = new Set<string>()
  ): Promise<any> {
    // 循環参照チェック
    if (visited.has(themePath)) {
      throw new Error(`Circular inheritance detected: ${themePath}`);
    }
    visited.add(themePath);
    
    // キャッシュチェック
    if (this.inheritanceCache.has(themePath)) {
      return this.inheritanceCache.get(themePath);
    }
    
    const themeData = await this.loadThemeFile(themePath);
    
    // 継承がない場合はそのまま返す
    if (!themeData.theme?.extends) {
      this.inheritanceCache.set(themePath, themeData.theme);
      return themeData.theme;
    }
    
    // 親テーマを再帰的に解決
    const parentPath = this.resolvePath(themeData.theme.extends, themePath);
    const parentTheme = await this.resolveInheritance(parentPath, visited);
    
    // 深いマージを実行
    const merged = this.deepMerge(parentTheme, themeData.theme);
    
    this.inheritanceCache.set(themePath, merged);
    return merged;
  }
  
  /**
   * 深いオブジェクトマージ
   */
  private deepMerge(parent: any, child: any): any {
    const result = { ...parent };
    
    for (const key in child) {
      if (key === 'extends') continue; // extendsは結果に含めない
      
      if (child[key] && typeof child[key] === 'object' && !Array.isArray(child[key])) {
        result[key] = this.deepMerge(result[key] || {}, child[key]);
      } else {
        result[key] = child[key];
      }
    }
    
    return result;
  }
}
```

### 2. **スキーマ拡張**

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "TextUI Designer Theme Schema (with Inheritance)",
  "type": "object",
  "properties": {
    "theme": {
      "type": "object",
      "properties": {
        "extends": {
          "type": "string",
          "description": "継承元テーマファイルのパス（相対パス）",
          "examples": [
            "./base-theme.yml",
            "../shared/corporate-theme.yml",
            "npm:@company/design-system"
          ]
        },
        "mergeStrategy": {
          "type": "object",
          "description": "プロパティ別のマージ戦略設定",
          "patternProperties": {
            ".*": {
              "enum": ["merge", "replace"],
              "default": "merge"
            }
          }
        }
        // ... 既存のプロパティ
      }
    }
  }
}
```

### 3. **バリデーション機能**

```typescript
/**
 * 継承チェーンの整合性をチェック
 */
export class ThemeInheritanceValidator {
  /**
   * 循環参照をチェック
   */
  static checkCircularInheritance(themePath: string): void {
    // DFS で循環検出
  }
  
  /**
   * 継承ファイルの存在チェック
   */
  static async validateInheritanceChain(themePath: string): Promise<string[]> {
    // 不正なパスや存在しないファイルを検出
  }
  
  /**
   * テーマ構造の整合性チェック
   */
  static validateThemeStructure(theme: any): ValidationResult {
    // 必須プロパティや型の検証
  }
}
```

---

### 1. **企業デザインシステム**

```yaml
# design-system/base.yml（全社共通）
theme:
  name: "Company Design System"
  tokens:
    color:
      primary: "#1E40AF"      # コーポレートブルー
      secondary: "#64748B"    # ニュートラルグレー
    typography:
      fontFamily:
        primary: "'Inter', sans-serif"
    spacing: { ... }

---

# products/crm/theme.yml（CRM専用）
theme:
  name: "CRM Theme"
  extends: "../../design-system/base.yml"
  tokens:
    color:
      accent: "#10B981"       # CRM固有のアクセントカラー
  components:
    button:
      cta:                    # CRM固有のCTAボタン
        backgroundColor: "var(--color-accent)"

---

# products/analytics/theme.yml（分析ツール専用）
theme:
  name: "Analytics Theme"
  extends: "../../design-system/base.yml"
  tokens:
    color:
      accent: "#F59E0B"       # Analytics固有のアクセントカラー
    spacing:
      lg: "2rem"              # より大きなスペーシング
```

### 2. **ダークモード対応**

```yaml
# themes/light-base.yml
theme:
  name: "Light Base"
  tokens:
    color:
      surface: "#FFFFFF"
      text:
        primary: "#111827"

---

# themes/dark.yml
theme:
  name: "Dark Theme"
  extends: "./light-base.yml"
  tokens:
    color:
      surface: "#1F2937"      # 背景を暗く
      text:
        primary: "#F9FAFB"    # テキストを明るく
      # その他の色は継承される
```

### 3. **段階的カスタマイズ**

```yaml
# base-material.yml（Material Design基盤）
theme:
  name: "Material Design Base"
  tokens:
    borderRadius:
      sm: "4px"
      md: "8px"
    shadows:
      md: "0 4px 6px rgba(0,0,0,0.1)"

---

# material-custom.yml（少しカスタマイズ）
theme:
  name: "Custom Material"
  extends: "./base-material.yml"
  tokens:
    color:
      primary: "#FF5722"      # プライマリカラーのみ変更

---

# material-branded.yml（ブランド適用）
theme:
  name: "Branded Material"
  extends: "./material-custom.yml"
  tokens:
    typography:
      fontFamily:
        primary: "'Roboto Slab', serif"  # ブランドフォント追加
```

---

### 1. **パフォーマンス最適化**

- **継承キャッシュ**: 解決済み継承チェーンをメモリキャッシュ
- **ファイル監視**: 継承チェーン内のファイル変更を自動検出
- **遅延解決**: 必要な時点でのみ継承を解決
- **循環参照検出**: O(n) での効率的な循環検出アルゴリズム

### 2. **エラーハンドリング**

```typescript
export enum ThemeInheritanceError {
  CIRCULAR_INHERITANCE = 'CIRCULAR_INHERITANCE',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  INVALID_EXTENDS_PATH = 'INVALID_EXTENDS_PATH',
  PARSING_ERROR = 'PARSING_ERROR'
}

export class ThemeInheritanceException extends Error {
  constructor(
    public type: ThemeInheritanceError,
    public themePath: string,
    public inheritanceChain: string[]
  ) {
    super(`Theme inheritance error: ${type} in ${themePath}`);
  }
}
```

### 3. **VS Code統合**

- **IntelliSense拡張**: `extends` プロパティでのファイルパス補完
- **継承チェーン表示**: ホバー時に継承関係を表示
- **エラー診断**: 循環参照や不正パスをリアルタイム検出
- **Go to Definition**: 継承元テーマファイルへのジャンプ

---

### Phase 1: 基本継承機能（MVP）
- [ ] `extends` キーワードサポート
- [ ] 単一継承での深いマージ機能
- [ ] 循環参照検出
- [ ] 基本的なエラーハンドリング

### Phase 2: 高度な継承機能
- [ ] 多重継承（チェーン継承）サポート
- [ ] マージ戦略の選択機能
- [ ] 継承キャッシュ最適化
- [ ] ファイル監視による自動更新

### Phase 3: 開発者体験向上
- [ ] スキーマ拡張（`extends` のIntelliSense）
- [ ] 継承チェーン可視化
- [ ] エラー診断の強化
- [ ] パフォーマンス監視機能

### Phase 4: エコシステム統合
- [ ] npm パッケージからの継承
- [ ] Git サブモジュール対応
- [ ] 継承関係のドキュメント自動生成
- [ ] テーママーケットプレイス連携

---

### **開発効率の向上**
- **再利用性**: 共通テーマを複数プロジェクトで活用
- **保守性**: 基底テーマの変更が派生テーマに自動反映
- **一貫性**: デザインシステムの統一が自動保証

### **大規模開発対応**
- **チーム協調**: デザインチーム→基底テーマ、開発チーム→カスタマイズ
- **複数プロダクト**: 企業内での統一デザインシステム構築
- **段階的適用**: 既存テーマからの段階的移行

### **柔軟性**
- **部分カスタマイズ**: 必要な部分のみを上書き
- **継承チェーン**: 複数段階の継承関係
- **後方互換性**: 既存テーマファイルとの完全互換

---

### 1. **条件付き継承**
```yaml
theme:
  extends: 
    - path: "./base.yml"
      condition: "screen.width > 768px"  # レスポンシブ継承
    - path: "./mobile.yml"
      condition: "screen.width <= 768px"
```

### 2. **動的継承**
```yaml
theme:
  extends: "{{ userPreferences.baseTheme }}"  # 実行時決定
```

### 3. **継承の可視化ツール**
- テーマ継承関係のグラフ表示
- 継承元の変更影響範囲の可視化
- テーマ差分の比較表示

---

**このテーマ継承システムにより、TextUI Designerは小規模な個人プロジェクトから大規模な企業システムまで、あらゆる規模でのデザインシステム構築を支援する包括的なソリューションとなります。**
