### ISSUE TITLE
テンプレート参照・UI分割統合システムの実装

### ISSUE THREAD

**Issue by kamoshika-san** [kamoshika-san/TextUI-Designer#45]
## 概要

TextUI Designerに**テンプレート参照機能**を実装し、大規模なUIを複数のファイルに分割して管理できるようにします。

単一ファイルでの開発限界を解決し、再利用可能なUI部品の作成、チーム開発での並行作業、保守性の向上を実現します。これにより、小規模なプロトタイプから大規模なアプリケーションまで、スケーラブルな開発体験を提供します。

---

### 現在の制約と課題

**単一ファイル制約による問題点：**

1. **ファイルサイズの肥大化**
   - 大規模UIで1つの`.tui.yml`が数百〜数千行になる
   - 編集・ナビゲーションが困難
   - VS Codeでの動作が重くなる

2. **再利用性の欠如**
   - 共通UI部品を毎回コピー&ペースト
   - 同じコンポーネントの修正が複数箇所に必要
   - DRY原則に反する開発スタイル

3. **チーム開発の困難**
   - 複数人が同一ファイルを編集 → 競合頻発
   - 機能単位での分担作業ができない
   - レビューが困難（差分が混在）

4. **保守性の低下**
   - 大きなファイルでのバグ発見が困難
   - 影響範囲の特定が複雑
   - リファクタリングのリスクが高い

### 実際のプロジェクトでの問題例

```yaml
# 現在：巨大な single-page.tui.yml (500+ lines)
page:
  id: dashboard
  components:
    # ヘッダー部分 (50 lines)
    - Container:
        id: header
        components:
          - Text: { variant: h1, value: "ダッシュボード" }
          - Button: { kind: primary, label: "新規作成" }
          # ... 50行続く
    
    # サイドバー部分 (100 lines)  
    - Container:
        id: sidebar
        components:
          # ... 100行続く
    
    # メインコンテンツ (200 lines)
    - Container:
        id: main-content
        components:
          # ... 200行続く
    
    # フッター部分 (50 lines)
    - Container:
        id: footer
        components:
          # ... 50行続く
```

**このファイルを5人のチームで編集 → 常にコンフリクト発生**

---

### 1. **テンプレート参照機能 (`$include`)**

> **ファイル拡張子の使い分け**
> - `.tui.yml`: 完全なUI定義スキーマに準拠するメインファイル（page要素必須）
> - `.template.yml`: 部分的なコンポーネント定義（componentsの配列として機能）

#### 基本構文
```yaml
# main.tui.yml
page:
  id: dashboard
  components:
    - $include: "./components/header.template.yml"
    - $include: "./components/sidebar.template.yml"  
    - $include: "./components/main-content.template.yml"
    - $include: "./components/footer.template.yml"
```

#### 分割されたテンプレートファイル
```yaml
# components/header.template.yml
- Container:
    id: header
    layout: horizontal
    components:
      - Text:
          variant: h1
          value: "ダッシュボード"
      - Button:
          kind: primary
          label: "新規作成"

---

# components/sidebar.template.yml  
- Container:
    id: sidebar
    components:
      - Text: { variant: h3, value: "メニュー" }
      - Button: { kind: secondary, label: "設定" }
      # ... ナビゲーション要素
```

#### パラメータ付きインクルード
```yaml
# main.tui.yml
page:
  components:
    - $include: 
        template: "./templates/card.template.yml"
        params:
          title: "売上データ"
          content: "今月の売上は..."
          variant: "success"
    
    - $include:
        template: "./templates/card.template.yml" 
        params:
          title: "在庫状況"
          content: "在庫不足の商品が..."
          variant: "warning"
```

#### テンプレートファイル
```yaml
# templates/card.template.yml
- Container:
    id: "card-{{ $params.title | slugify }}"
    components:
      - Text:
          variant: h3
          value: "{{ $params.title }}"
      - Text:
          value: "{{ $params.content }}"
      - Alert:
          variant: "{{ $params.variant }}"
          message: "詳細を確認してください"
```

### 3. **ネストした参照とスコープ管理**

```yaml
# layouts/dashboard-layout.template.yml
- Container:
    layout: vertical
    components:
      - $include: "./shared/navigation.template.yml"
      - Container:
          layout: horizontal
          components:
            - $include: 
                template: "./shared/sidebar.template.yml"
                params:
                  items: "{{ $params.sidebarItems }}"
            - $include: "{{ $params.mainContent }}"  # 動的パス
      - $include: "./shared/footer.template.yml"

---

# pages/user-management.tui.yml
page:
  id: users
  components:
    - $include:
        template: "./layouts/dashboard-layout.template.yml"
        params:
          sidebarItems:
            - { label: "ユーザー一覧", href: "/users" }
            - { label: "権限管理", href: "/permissions" }
          mainContent: "./content/user-list.template.yml"
```

### 4. **コンディショナル インクルード**

```yaml
# responsive-layout.tui.yml
page:
  components:
    # デスクトップ用レイアウト
    - $include:
        template: "./layouts/desktop-layout.template.yml"
        condition: "screen.width >= 1024px"
    
    # タブレット用レイアウト  
    - $include:
        template: "./layouts/tablet-layout.template.yml"
        condition: "screen.width >= 768px && screen.width < 1024px"
    
    # モバイル用レイアウト
    - $include:
        template: "./layouts/mobile-layout.template.yml"
        condition: "screen.width < 768px"
```

---

### 1. **ファイル構造規約**

```
project/
├── pages/                        # メインページファイル（完全UI定義）
│   ├── dashboard.tui.yml         
│   ├── user-list.tui.yml         
│   └── settings.tui.yml          
├── components/                   # 再利用可能コンポーネントテンプレート
│   ├── header.template.yml        
│   ├── sidebar.template.yml       
│   └── card.template.yml          
├── layouts/                      # レイアウトテンプレート
│   ├── dashboard-layout.template.yml
│   └── modal-layout.template.yml  
├── templates/                    # パラメータ化テンプレート
│   ├── form-template.template.yml 
│   └── list-template.template.yml 
└── shared/                       # 共通コンポーネント
    ├── navigation.template.yml    
    └── footer.template.yml        
```

#### スキーマ検証とIntelliSense
```typescript
// package.json での言語サービス設定
{
  "contributes": {
    "languages": [
      {
        "id": "tui-template",
        "extensions": [".template.yml"],
        "aliases": ["TextUI Template"]
      }
    ],
    "jsonSchemas": [
      {
        "fileMatch": ["*.tui.yml"],
        "url": "./schemas/schema.json"     // 完全UI定義スキーマ
      },
      {
        "fileMatch": ["*.template.yml"], 
        "url": "./schemas/template-schema.json"   // 部分コンポーネントスキーマ
      }
    ]
  }
}
```

#### 変数展開
```yaml
# テンプレートファイル内での変数参照
- Text:
    value: "{{ $params.userName }}さん、こんにちは"  # パラメータ参照
    class: "{{ $theme.colors.primary }}"            # テーマ参照
    id: "welcome-{{ $context.pageId }}"             # コンテキスト参照
```

#### 条件分岐
```yaml
# 条件付きコンポーネント
- $if: "{{ $params.showButton }}"
  then:
    - Button:
        label: "{{ $params.buttonLabel }}"
        kind: "{{ $params.buttonKind || 'primary' }}"
  else:
    - Text:
        value: "ボタンは非表示です"
```

#### ループ処理
```yaml
# 配列データの繰り返し
- $foreach: "{{ $params.items }}"
  as: "item"
  template:
    - Container:
        components:
          - Text: { value: "{{ item.name }}" }
          - Text: { value: "{{ item.description }}" }
```

#### キャッシュ機能
```typescript
export class TemplateCache {
  private cache = new Map<string, ParsedTemplate>();
  private dependencies = new Map<string, Set<string>>();
  
  /**
   * テンプレートの解析結果をキャッシュ
   */
  async getTemplate(path: string): Promise<ParsedTemplate> {
    if (this.cache.has(path)) {
      return this.cache.get(path)!;
    }
    
    const template = await this.parseTemplate(path);
    this.cache.set(path, template);
    return template;
  }
  
  /**
   * 依存関係の変更時にキャッシュを無効化
   */
  invalidateCache(changedPath: string): void {
    const dependents = this.dependencies.get(changedPath) || new Set();
    for (const dependent of dependents) {
      this.cache.delete(dependent);
    }
  }
}
```

#### 循環参照検出
```typescript
/**
 * テンプレート参照の循環を検出
 */
export class CircularReferenceDetector {
  static checkCircularReference(
    templatePath: string, 
    visited = new Set<string>()
  ): void {
    if (visited.has(templatePath)) {
      throw new TemplateError(
        `Circular reference detected: ${Array.from(visited).join(' -> ')} -> ${templatePath}`
      );
    }
    
    visited.add(templatePath);
    // 依存関係を再帰的にチェック
  }
}
```

#### IntelliSense拡張
```typescript
/**
 * テンプレート参照のパス補完
 */
export class TemplatePathCompletionProvider {
  provideCompletionItems(
    document: vscode.TextDocument,
    position: vscode.Position
  ): vscode.CompletionItem[] {
    // $include: のパス部分で候補を表示
    return this.getAvailableTemplates(document.uri);
  }
}
```

#### Go to Definition
```typescript  
/**
 * テンプレート参照から定義元へジャンプ
 */
export class TemplateDefinitionProvider {
  provideDefinition(
    document: vscode.TextDocument,
    position: vscode.Position
  ): vscode.Location | undefined {
    const templatePath = this.extractTemplatePath(document, position);
    return new vscode.Location(vscode.Uri.file(templatePath), new vscode.Position(0, 0));
  }
}
```

---

#### プロジェクト構成
```
dashboard-project/
├── main.tui.yml                      # エントリーポイント（完全UI定義）
├── layouts/
│   └── dashboard.template.yml        # 基本レイアウトテンプレート
├── widgets/                          # ダッシュボードウィジェットテンプレート
│   ├── sales-chart.template.yml   
│   ├── user-stats.template.yml    
│   └── notification-panel.template.yml
└── shared/
    ├── header.template.yml        
    └── sidebar.template.yml       
```

#### チーム分担
- **Aさん**: `layouts/` とメインページ（`.tui.yml`）
- **Bさん**: `widgets/sales-chart.template.yml`
- **Cさん**: `widgets/user-stats.template.yml` 
- **Dさん**: `shared/` コンポーネントテンプレート

**→ 競合なしで並行開発可能**

### 2. **コンポーネントライブラリ開発**

```yaml
# templates/data-table.template.yml（再利用可能なテーブルテンプレート）
- Container:
    components:
      # ヘッダー
      - Container:
          layout: horizontal
          components:
            - Text: { variant: h3, value: "{{ $params.title }}" }
            - Button: 
                label: "{{ $params.actionLabel || '新規追加' }}"
                kind: primary
      
      # テーブル本体
      - $foreach: "{{ $params.columns }}"
        as: "column"
        template:
          - Text: { value: "{{ column.header }}" }
      
      - $foreach: "{{ $params.data }}"
        as: "row"
        template:
          - Container:
              layout: horizontal
              components:
                - $foreach: "{{ $params.columns }}"
                  as: "column" 
                  template:
                    - Text: { value: "{{ row[column.key] }}" }

---

# pages/user-list.tui.yml（利用側）
page:
  components:
    - $include:
        template: "./templates/data-table.template.yml"
        params:
          title: "ユーザー一覧"
          columns:
            - { key: "name", header: "名前" }
            - { key: "email", header: "メール" }
            - { key: "role", header: "権限" }
          data:
            - { name: "田中太郎", email: "tanaka@example.com", role: "管理者" }
            - { name: "佐藤花子", email: "sato@example.com", role: "一般" }
```

### 3. **多言語対応アプリケーション**

```yaml
# templates/localized-form.template.yml
- Form:
    id: contact-form
    fields:
      - Input:
          label: "{{ $i18n.form.name }}"
          name: name
          placeholder: "{{ $i18n.form.namePlaceholder }}"
      - Input:
          label: "{{ $i18n.form.email }}"
          name: email
          type: email
    actions:
      - Button:
          label: "{{ $i18n.form.submit }}"
          kind: primary
          submit: true

---

# pages/contact-ja.tui.yml（日本語版）
page:
  components:
    - $include:
        template: "./templates/localized-form.template.yml"
        params:  
          $i18n:
            form:
              name: "お名前"
              namePlaceholder: "山田太郎"
              email: "メールアドレス"
              submit: "送信"

---

# pages/contact-en.tui.yml（英語版）
page:
  components:
    - $include:
        template: "./templates/localized-form.template.yml"
        params:
          $i18n:
            form:
              name: "Name"
              namePlaceholder: "John Doe"
              email: "Email Address" 
              submit: "Submit"
```

---

### Phase 1: 基本インクルード機能（MVP）
- [x] `$include` 構文の基本実装
- [x] 単純なファイル参照機能（`.template.yml`対応）
- [x] `.template.yml`用スキーマ作成とIntelliSense対応
- [x] 循環参照検出
- [x] エラーハンドリング

### Phase 2: パラメータ化テンプレート
- [x] `params` による変数渡し
- [x] テンプレート内変数展開 (`{{ $params.xxx }}`)
- [x] 基本的な条件分岐 (`$if`)
- [x] 配列ループ処理 (`$foreach`)

### Phase 3: 高度なテンプレート機能
- [ ] ネストした参照のサポート
- [ ] 動的パス解決
- [ ] コンディショナル インクルード
- [ ] テンプレートの継承機能

### Phase 4: 開発者体験・パフォーマンス
- [x] VS Code IntelliSense 完全対応
- [x] Go to Definition 機能
- [ ] テンプレートキャッシュ最適化  
- [ ] ホットリロード対応

### Phase 5: エコシステム統合
- [ ] npm パッケージからのテンプレート参照
- [ ] テンプレートのバージョン管理
- [ ] コンポーネントライブラリマーケット
- [ ] デバッグツール・可視化

---

### 1. **パフォーマンス**

- **解析キャッシュ**: 一度解析したテンプレートをメモリキャッシュ
- **遅延読み込み**: 実際に参照されるまでファイル読み込みを遅延
- **差分更新**: 変更されたファイルのみ再解析
- **並列処理**: 独立したテンプレートの並列読み込み

### 2. **エラーハンドリング**

```typescript
export enum TemplateError {
  FILE_NOT_FOUND = 'TEMPLATE_FILE_NOT_FOUND',
  CIRCULAR_REFERENCE = 'CIRCULAR_REFERENCE', 
  SYNTAX_ERROR = 'TEMPLATE_SYNTAX_ERROR',
  PARAMETER_MISSING = 'REQUIRED_PARAMETER_MISSING',
  TYPE_MISMATCH = 'PARAMETER_TYPE_MISMATCH'
}

export class TemplateException extends Error {
  constructor(
    public type: TemplateError,
    public templatePath: string,
    public line?: number,
    public column?: number
  ) {
    super(`Template error in ${templatePath}: ${type}`);
  }
}
```

### 3. **セキュリティ**

- **パストラバーサル防止**: `../../../etc/passwd` 等の不正パス検出
- **実行制限**: テンプレート内での任意コード実行を防止
- **サンドボックス化**: テンプレート評価の安全な実行環境

---

### **開発効率の向上**
- **モジュラー開発**: 機能単位での分割開発
- **再利用性**: 共通コンポーネントの効率的な活用
- **並行作業**: チームメンバーの競合なし開発

### **保守性の向上**  
- **責任の分離**: 各ファイルが明確な責任を持つ
- **影響範囲の限定**: 変更が他部分に与える影響を最小化
- **テストしやすさ**: 小さな単位でのテスト作成

### **スケーラビリティ**
- **大規模アプリケーション対応**: 数百画面でも管理可能
- **チーム拡張**: 10人以上のチームでの開発支援
- **長期メンテナンス**: 年単位の開発プロジェクトに対応

### **開発者体験の向上**
- **明確なファイル役割**: `.tui.yml`（完全UI）と`.template.yml`（部分テンプレート）の区別
- **適切なスキーマ検証**: ファイルタイプに応じた専用スキーマでより正確な補完・検証
- **VS Code統合**: 拡張子ベースの言語サービス最適化

---

### 1. **AIアシスト機能**
- テンプレートの自動生成
- 最適な分割パターンの提案
- 重複コードの自動検出・統合提案

### 2. **ビジュアル編集**
- テンプレート依存関係のグラフ表示
- ドラッグ&ドロップによるテンプレート組み合わせ
- リアルタイムプレビューでの編集

### 3. **プロダクション対応**
- テンプレートの事前コンパイル
- 配布用バンドルの最適化
- CDN対応とキャッシュ戦略

---

**このテンプレート参照システムにより、TextUI Designerは小規模なプロトタイプから大規模なエンタープライズアプリケーションまで、実際のプダクション開発で使用可能な本格的な開発環境となります。**
